#!/bin/bash

# metadata prints the value associated with the named metadata key on this VM.
metadata() {
	curl http://metadata/computeMetadata/v1/instance/attributes/$1 -H "Metadata-Flavor: Google"
}

set -e
server=$(metadata server)

# initialize /work
rm -rf /work
mkdir -p /work
cd /work
gsutil cp $server /work/server
chmod +x /work/server

cron=$(metadata cron)
if [ "$cron" != "" ]; then
	(
	# for cron jobs
	apt-get update
	apt-get -y install git
	git clone https://go.googlesource.com/go /work/go

	mkdir /work/cron
	gsutil -m rsync -r $cron/ /work/cron
	chmod 600 /work/cron/.github*
	chmod +x /work/cron/exe/*
	crontab /work/cron/crontab
	) &
fi

# run server in a loop, sleeping 5 seconds between restarts.
# if the loop ever stops, reboot the machine.
# this happened once, for reasons unclear.
(
	set +e
	while true
	do
		./server
		sleep 5
	done >log 2>&1 &
	wait
	shutdown -r now
) &
exit 0
